labels.json
=> Add kokoro:force-run label

users.json
=> add the right beccca

users.json
Add Jesse Lovelace to yoshi and yoshi-java
=> Add Jesse Lovelace to yoshi and yoshi-java

src/cli.ts, src/slo.ts, src/types.ts
=> feat: split SLOs into `languages` and `apis`

users.json
Add java resource name in users.json
=> Add QLogic java resource names

test/verifyConfigs.test.ts
=> add tests to verify json configs are valid

src/issue.ts, src/slo.ts, src/types.ts
For the fixit. Now you can say:
```sh
sloth languages --type question,docs
```
=> fix: allow passing multiple types

CHANGELOG.md, package.json, samples/package.json
This pull request was generated using releasetool.
=> Release @justinbeckwith/sloth v2.2.0

src/issue.ts, src/slo.ts
=> fix: fix the linter

CHANGELOG.md, package.json, samples/package.json
This pull request was generated using releasetool.
=> Release @justinbeckwith/sloth v2.1.1

users.json
@andrewsg will be managing the ndb work.
Fixes #107
=> Adding andrewsg to yoshi-python

users.json
=> Add andrey-qlogic to yoshi-java

users.json
=> add frankyn to yoshi-go

CHANGELOG.md, package.json, samples/package.json
This pull request was generated using releasetool.
=> Release @justinbeckwith/sloth v2.1.2

users.json
=> add seth and noah for reviews

users.json
=> Add Billy Jacobson

users.json
/cc @JustinBeckwith @theacodes
=> Add scheduler to list of PHP repos

src/util.ts
=> fix: use latest auth method for octokit

users.json
=> remove enocom@

repos.json, users.json
=> Add autoML PHP repo

users.json
@JustinBeckwith Is this something we can do?
cc @jqll @aalexand @kalyanac
=> add new team for profiler folks working on Go

users.json
Remove some inactive users, and add new team members.
/cc: @devjgm
=> Update yoshi-cpp members.

users.json
=> Fix users.json

users.json
=> Adding olavloite to the java team

users.json
👋 I've added myself to the languages I feel comfortable working in currently:
* *nodejs*: I would rate myself an `A+`, please lean on me for code reviews.
* *python/ruby*: I'd give myself a `B`; excited to help with code review, and perhaps dust off my knowledge of the languages.
* *cpp*: I'd give myself a `C`; I've been trying to write as much C++ as possible and am excited to learn more.
I'm very excited to be joining @googleapis/yoshi thanks for having me.
=> chore: add bcoe to python, ruby, cpp, nodejs

users.json
=> Added andrei-semeniuk to yoshi team

users.json
This will require adding @odeke-em to the googleapis org.
=> add Emmanuel to Go

users.json
So I can have access to google-cloud-java-private.
=> Add andreamlin to yoshi-java

users.json
@JustinBeckwith, @crwilcox PTAL.
=> Add Peter Lamut to yoshi-python

users.json
I work on `google-cloud-bigquery`
=> Add alixhami to python

users.json
@anguillanneuf needs access to google-cloud-python to work on Pub/Sub issues.
=> Add anguillanneuf to yoshi-python.

repos.json
Autorelease determines the repo language by looking at `repos.json`. 
CC @crwilcox
=> Add python-ndb.

repos.json, users.json
Add our new `release-please` project:
=> chore: add release-please to repos

users.json
Change github account name from 'praveenqlogic' -> to 'praveenqlogic01'
=> chore: update github userID

repos.json
=> feat: add phishing protection

src/label.ts
This adds a list of labels we want to actively delete from repositories when we run the `sloth labels` command.
=> feat: remove labels we do not want

.kokoro/release/tag-issues.cfg, .kokoro/tag-issues.sh
Waiting for key to be available in keystore.
=> build: add DRIFT key to kokoro job

users.json
Noah is the AniML DPE working on Python.
=> Add nnegrey to yoshi-python.

users.json
Abhinav is a contractor working on storage and database general issues.
=> Adding `abhinav-qlogic` to `yoshi-java`

users.json
=> Add tmatsuo to yoshi-cpp

teams.json
=> fix: move ndb api to cbr team

users.json
@chingor13 It would be convenient to branch instead of fork.
=> Add @elharo to yoshi-java

users.json
🍺 🍺  thanks for the awesome work folks!
=> chore: remove theacodes and sduskis

users.json
For @sirtorry to be added as a reviewer to https://github.com/googleapis/google-cloud-python/pull/8720
=> Add sirtorry to yoshi-python

repos.json, src/users.ts, users.json
This fixed a few issues I ran into while making `sloth repos` work again.
=> fix: clean up sloth repos

users.json
=> feat: remove abhinav and paras

repos.json, teams.json
Warm welcome to the onramp team!
=> feat: add the onramp repos and team

repos.json, teams.json, users.json
We're spinning up a new BigQuery C++ client.
FYI @coryan @devjgm
=> feat: Add new google-cloud-cpp-bigquery repository

users.json
Adds surferjeffatgoogle to our Node.js and yoshi lists.
=> feat: add surferjeffatgoogle to Node.js and yoshi

labels.json
Related to https://github.com/googleapis/repo-automation-bots/pull/125.
=> feat: add kokoro:run label

users.json
=> chore: remove jmdobry from Node.js team

users.json
=> feat: adding sofia to sloth users.json

users.json
Adding @xiaozhenliu-gg5 to `yoshi-nodejs`
=> chore: add xiaozhenliu-gg5 to yoshi-nodejs

users.json
Chen is working 20% on the Python auth libraries 🎉 
CC. @michaelawyu
=> chore: add michaelawyu (chenyumic) to yoshi-python

users.json
Adding @steffnay to yoshi-nodejs
=> chore: add steffnay to yoshi-nodejs

users.json
Need write access to change labels of issues during triage.
=> chore: add benwhitehead to yoshi-nodejs team

repos.json
=> fix: correct repo name for nodejs-datastore-kvstore

users.json
we should have also updated the entry on users.json.
=> fix: kvstore should also be updated in users.json

users.json
Leah will be the new AniML point of contact.
=> chore: add leahecole to yoshi-python

users.json
Added myself to yoshi-nodejs users
=> chore: add AlanGasperini to yoshi-nodejs

users.json
Adds noahdietz to the yoshi-php group.
=> chore: add noahdietz to yoshi-php

users.json
This is just adding me to the perms for nodejs-pubsub so I can do my work there. Thanks!
=> chore: add feywind to the yoshi-nodejs group permissions

users.json
Add frankyn to yoshi-java team.
=> feat: add frankyn to yoshi-java team

users.json
=> fix: remove jadekler from yoshi groups

repos.json, users.json
add the new googleapis/nodejs-recommender repo.
=> feat: add new googleapis/nodejs-recommender repo

repos.json, teams.json, users.json
We just added the google-cloud-cpp-pubsub repository.
=> feat: add google-cloud-cpp-pubsub repository

users.json
=> fix: add fhinkel to yoshi-nodejs team

users.json
=> feat: add ava12 to yoshi-php team

users.json
=> feat: add summer in users.json

package.json, src/users.ts
Octokit is a great reminder of how much customers love modules that ship API breaking changes ḁ̵̻͉̞̩̼̫͍̭̬̘͖͇̃̓̓̈́͐̓̋́͘͜n̸͈̝͖̺̟͇̤̾̕ ̷̡̱͕̬̱̗̗̮̺͈̦̘̎͛ͅn̶̡̡̢̢͓͎̜̼̳̗͕̞̟͌p̶̢̨̗̥̞̜̭̞̫͈͍͉̣͊͒̽̍̚m̸̨̱̱͈̱̯̫̉͋͐̈͒̈́͐͛̓͋̑̆̈́͊͠ ̵̛̛̙͗̀͊̑̎̌̒̆̎̎͂͝m̶̱͎̭̮̯͕̘͎̻͂̈͊͆̅̅̆̇̕̕͘̚ờ̶̞̮͈̙͍̪͙̥̦̌́͋̆̎͆̾͆̈́͘͝͝d̷̝̮̩̼͎̠̻͕̠͍̲͔̗̔̀̇̄́̉̈́ư̴̙̦͈̭̞̘͙̈̉̇̋̂̀͊̉͛̂̀͘͝ͅļ̸͍͇̖͉̀̓e̷̥̠̤͋͐̀͒̂̑̀̍̿̃͘͝ ̶̨̬͈̜̬̼͙͙͖̭͉͓̠͖̌͐̆̄̅̕ͅṯ̴͓̖̘̀̎̊͑̿̀̉͛̓̾̂̀̈́̕̚ḩ̷̨͔̩̟̲͌̉͌͌͂̑͐̇̂̋͋̕͠a̷̛̱͈͙͖̞̹̜̿͗͒̏̒̑̈́̀͌̕t̵̨́̉̓̈́̈́̇̍̆͆̀͆͘ ̶̨̨͙̼̻͉̠͖̯͚̂̒͐͑̽̾̉̾̂́ṁ̶̙̙̞̺͉̺̪̟̣̞̱̽̔͛̆̎̈́̋̀̀̐̕͘͠ả̶̢̛̻̝̦̬̜̲̲̥̯̖̩̭͚̒̈́͐͋̎͗̋ͅk̷̯̘̖̲̺̽͆̈́̒ê̴̙̥̹͎̊̈́̽͋́̕s̵͚̭̥͎̜̰̾ͅ ̷͙͕̥͚͇͛͒͊̒̑c̴͙̲̠̖͓͎̫̜̐͒̀̇͊̂̐͊̊̔̿͑ȯ̶̡̝̘͔̥̂͑̉͑̇̅̕ň̷͖̺̤͙͈̜̋̀̐́̽̔̋̓͘͝͝͝ͅṣ̶͈̳̺͇̫̜̝̰̩̹̉̏̒̏͛͌̔͜ͅṯ̴̳͒̽͂̎͘a̷̧̛͓̜͎̋͒̓̊̉͂̑̌̿͐͒̓̚ṇ̵̢̼̘͙͔̼̬̙̜̹̮̯̳̀̂̀͝t̸̨̡̧̤̮̮̣̭̫͖̜̮̑̇̐͌ͅͅ ̴̛̘̦̊̓͝͝b̵̧̨͚̺̺̳̄͆̍́͑̓̓̂r̵̡̝̰̪̠̭̟̥̭̬̤̞̤͖͋͂͛͑̽̋̒͛̓̈̅̕ë̴̢̧̮̲̺̼̣͚̻̪́̆̈́̀̅̋ͅȃ̸̒͂̇͆̔́͌̈́͝ …
=> fix(deps): upgrade to latest version of octokit

users.json
=> feat: add viacheslav-rostovtsev to a ruby team in users.json

src/cli.ts, src/repos.ts
Eventual goal is for this to end up in a bot, but it's a lot easier to start here.  Ran this against all the nodejs repos, and so far so good :)
=> feat: add sync-repo-settings

users.json
Fix franknatividad -> frankyn :man_facepalming:
=> fix: frankyn github handle

users.json
=> chore: add kolea2 to yoshi-python

repos.json
=> feat: add java-accessapproval repository

repos.json, users.json
=> chore: add python-access-approval repo

repos.json
=> feat: add nodejs-bigquery-storage to repos.json

users.json
=> fix: add Andrew Zammit (zamnuts) to yoshi-nodejs team

repos.json
Not sure how we missed this one
=> feat: track java-datastore repo

users.json
cc @arithmetic1728. Sijun is on ACTools and will be working on the Python auth library.
=> feat: add arithmetic1728 to yoshi-python

required-checks.json
so googleapis/google-api-ruby-client can have merge-on-green
=> feat: add required checks for google-api-ruby-client

repos.json
Adds Cloud Game Servers to repos.json file.
=> fix: add nodejs game servers repo

users.json
Adds the googleapis/nodejs-game-servers repo to users.json file
=> feat: updates users.json to include Game Servers

users.json
=> feat: add bigquery-storage

required-checks.json, teams.json
@kurtisvg @crwilcox @busunkim96
=> fix: remove 3.5 kokoro requirement

src/issue.ts
=> fix: attributes team by repo before api

users.json
Adding myself to yoshi users list. :)
=> feat: add meredithslota to yoshi

repos.json
=> chore: add nodejs-service-directory repo

repos.json
Adds new media-translation library.
=> feat: add nodejs-media-translation

repos.json, users.json
=> feat: add python-recaptcha-enterprise

repos.json, users.json
=> feat: add python-api-common-protos

repos.json, users.json
Add https://github.com/googleapis/python-test-utils/
=> feat: add python-test-utils

repos.json, users.json
=> chore: add python-bigquery-reservation

repos.json, users.json
Adds the `os-config` library for Node.js.
=> feat: add os-config

users.json
=> fix: adds intern to python

repos.json, users.json
=> feat: add python-bigquery-connection repo

repos.json
=> fix: add jsdoc-fresh repos

repos.json
This repo is now archived.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/sloth/689)
=> clean: remove the 'cpp-cmakefiles' repo

teams.json
=> chore: moves ndb to soda team

repos.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/sloth/694)
=> chore: remove google-cloud-cpp-spanner

users.json
=> feat: add xiaozhenliu to yoshi-python

repos.json, users.json
=> fix: add python-os-config repo

repos.json
fix: Adding two repos to enable SLO tracking for issues:
- GoogleCloudPlatform/cloud-code-samples
- GoogleCloudPlatform/stackdriver-sandbox
Fixes #707 🦕
=> fix: Adding stackdriver-sandbox and cloud-code-samples

teams.json
FYI @simonz130 
Also FYI @danoscarmike this is why the SLO metric is messed up
=> fix: include new CAKE repos in teams

users.json
Removes noahdietz from yoshi-php.
=> chore: remove noahdietz from yoshi-php

repos.json
=> chore: add nodejs-bigquery-connection

repos.json
=> chore: remove python-irm from repo list
