googleapis/sloth

- users.json
(Amanda is a permanent team member; Mike was 20% and is mostly rolling off, but is likely to still have occasional contributions around Bigtable.)
> Add Amanda Tarafa Mas and Mike Dour to Yoshi lists for .NET

- users.json
Adding QLogic java and nodejs devs.  Also, adding Igor Bernstein, a Googler who's working on the Java client.  This will allow their PRs to automatically invoke the testing pipeline.
> Adding QLogic java and node devs

- users.json
yoshi-kokoro's GitHub access token will be used for client library Kokoro runs.
> Add yoshi-kokoro as admin

- repos.json
- src/repos.ts
- users.json
As of right now, it looks like all of our repos are actually in the `googleapis` GitHub org!  This makes automation so much easier.
> chore: remove GoogleCloudPlatform org

- repos.json
- users.json
..once https://github.com/googleapis/nodejs-datalabeling is made public
> chore: add nodejs-datalabeling to sloth

- package.json
- src/issue.ts
- src/slo.ts
- src/types.ts
- test/fixtures/driftResponse.json
This moves us from using the raw GitHub API over towards using the DevRel GitHub Issues API.  This requires folks to set another API key, but it also is much faster, and doesn't kill the GitHub API quota or abuse limits.
> refactor: use drift API to get repo issues

- labels.json
- src/issue.ts
We discussed this today in the team meeting.  Issues that are blocked on an external API can now be tagged with the `external` label.  This will ensure they are not included in SLO calculations.
> feat: ignore external issues from SLO

- repos.json
@bcoe Is `cloudbuild` the only new repo we must add here?
> feat: add nodejs-cloudbuild

- repos.json
- users.json
This is the deprecated Python 2 oauth client, which has been replaced.  Just to make sure folks don't get confused, we went ahead and archived the repository.
> feat: stop tracking googleapis/oauth2client

- users.json
added folks to the teams that they need to write a release friction log on, we should merge this and run `sloth` so that folks don't bump into permission issues trying to walk through a release playbook.
> chore: add folks for release friction log

- repos.json
- users.json
fixes the link in sloth for gce-images, we will likely need to update kokoro too.
> fix: gce-images should now be nodejs-gce-images

- users.json
folks in the Node.js group don't have access to github-repo-automation for maintenance.
> fix: add github-repo-automation to nodejs group

- repos.json
- users.json
This module is no longer used, and we're archiving the repo.
> fix: drop nodejs-common-grpc module

- required-checks.json
This should let us handle this repo with merge-on-green.
> fix(java): add required-checks override for googleapis/google-api-java-client-services

- .github/workflows/nightly.yaml
- package.json
- src/exportToBigQuery.ts
- src/issue.ts
This sets up a nightly job, that will directly pipe raw sloth output into a BigQuery table.  This doesn't replace the other job, but gives us some ability to trend data beyond just OOSLO counts and total issue counts (specifically @leahecole was asking about trending open PRs).
> feat: add nightly snapshot job

- required-checks.json
Added the ability to use repo-native branch support in [this PR](https://github.com/googleapis/repo-automation-bots/pull/332)
Turning that functionality on for nodejs-docs-samples repo
> fix: add support for Node Support

- required-checks.json
This will (hopefully) enable `automerge` for green PR in https://github.com/googleapis/gapic-generator-typescript.
Cc: @xiaozhenliu-gg5 @summer-ji-eng FYI!
> chore: enable automerge for gapic-generator-typescript

- required-checks.json
cloud-trace-nodejs is still using CircleCI, I've opened a tracking issue:
https://github.com/googleapis/cloud-trace-nodejs/issues/1207
> fix: cloud-trace-nodejs has different requirements for tests

- users.json
> fix: remove tswast from yoshi teams

- src/issue.ts
Fixes: https://github.com/googleapis/sloth/issues/579
Reverts: googleapis/sloth#563
> fix: rollback "attributes team by repo before api"

- required-checks.json
Let's not accidentally mess with required checks when we update branch protection rules.
> chore: ignore nodejs-getting-started/nodejs-docs-samples when updating required checks

- repos.json
This repo has been archived https://github.com/googleapis/google-cloud-cpp-bigquery. Its contents has been moved into our C++ monorepo (https://github.com/googleapis/google-cloud-cpp). And our monorepo is already being tracked in this repos.json file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/sloth/631)
> fix: remove the google-cloud-cpp-bigquery repo

- repos.json
This repo has been archived https://github.com/googleapis/google-cloud-cpp-pubsub. Its contents have been moved into our C++ monorepo (https://github.com/googleapis/google-cloud-cpp). And our monorepo is already being tracked in this repos.json file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/sloth/643)
> fix: remove the google-cloud-cpp-pubsub repo

- users.json
I haven't been doing work on Ruby or dotnet repos, so let's not have me on the teams.
> fix: remove bcoe from teams they're not contributing to

- teams.json
The APM folks have taken ownership of Cloud Trace and Debug for node.js, and CAKE has taken ownership of error reporting all up.
> fix: update APM team attribution
